### ISSUE TITLE
Running multiple instances of application on 1 host

### ISSUE THREAD

**Issue by bweston92** [willrstern/production-docker-ha-architecture#1]
If I have 4 machines but want to deploy 10 instances I get port conflicts. How can I get the service discovery to find the port that docker has assigned to each instance?

Currently I have:
`docker inspect --format '{{ (index (index .NetworkSettings.Ports "3000/tcp") 0).HostPort }}' someapp`

But I feel there should be an easier way?

**Comment by willrstern** [comment]
If you're using flannel, you don't ever have to expose a port, each container will get it's own IP address which is direct access inside the container, so <ip>:3000.

A GREAT new Docker feature is
https://blog.docker.com/2015/11/docker-multi-host-networking-ga/

It is a HUGE problem solver removing the need for service registration and discovery!
Just add all apps to the same network and they can access each other by name via DNS.

**Comment by bweston92** [comment]
WOW, man that solves it all :/

**Comment by willrstern** [comment]
Pretty incredible, eh?  Now I have to re-do all my videos haha.

**Comment by bweston92** [comment]
Please let me know when you've got them up :D (I am subscribed but yeah)
