### ISSUE TITLE
Issue with weird

### ISSUE THREAD

**Issue by bweston92** [willrstern/production-docker-ha-architecture#2]
core@nellie ~ $ /usr/bin/ip route
default via 192.168.170.1 dev eth0  proto dhcp  src 192.168.170.96  metric 1024 
10.1.0.0/16 dev flannel0  proto kernel  scope link  src 10.1.15.0 
10.1.15.0/24 dev docker0  proto kernel  scope link  src 10.1.15.1 
192.168.170.0/24 dev eth0  proto kernel  scope link  src 192.168.170.96 
192.168.170.1 dev eth0  proto dhcp  scope link  src 192.168.170.96  metric 1024 

Command from load balancer:
`ExecStartPost=/usr/bin/sh -c "sleep 3 && curl -X PUT 192.168.170.209:2379/v2/keys/app -d value=$(/usr/bin/ip route|grep 'eth0.\+src' | head -1 | grep -o '[0-9\.]\+\s\+$' | grep -o '[0-9\.]\+'):$(/usr/bin/docker ps | grep 'app-lb' | grep -o '[0-9]\+->' | grep -o '[0-9]\+' | head -n 1)"`

Makes use of the `metric 1024` and uses that as ip address. Any ideas why I might be getting that metric instead of the actual ip address?

**Comment by willrstern** [comment]
See if this works:
`ifconfig | grep 'inet ' | grep 'broadcast' | grep -o '[0-9]\+\.[0-9]\+\.[0-9]\+\.[0-9]\+' | head -1`
Instead of this:
`/usr/bin/ip route|grep 'eth0.\+src' | head -1 | grep -o '[0-9\.]\+\s\+$' | grep -o '[0-9\.]\+'`

**Comment by bweston92** [comment]
I've actually modified it slightly `ifconfig eth0 | grep -o inet\ [0-9\.]\\\+ | cut -d ' ' -f 2` but thanks!
